#!/bin/sh
# Use livemedia-creator without virt to make a live iso
# NOTE: liveiso.ks needs to have url and repo setup correctly.

KS_PATH=liveiso.ks
RESULTS=/var/tmp/lmc-liveiso-results

# Are lorax and anaconda-tui installed?
rpm -q lorax anaconda-tui > /dev/null
if [ $? -gt 0 ]; then
    echo "Make sure lorax and anaconda-tui are installed"
    exit 1
fi

if [ ! -e "$KS_PATH" ]; then
    echo "$KS_PATH is missing"
    exit 1
fi

if [ -e "$RESULTS" ]; then
    echo "Previous results still at $RESULTS, move or delete them first"
    exit 1
fi

getenforce | grep Enforcing > /dev/null
if [ $? -eq 0 ]; then
    echo "SELinux needs to be Permissive or Disabled."
    exit 1
fi

sudo livemedia-creator --no-virt \
--title "Red Hat Enterprise Linux" --project "Red Hat Enterprise Linux" --releasever 7.4 \
--make-iso  \
--resultdir $RESULTS \
--ks=$KS_PATH |& tee lmc-build-out.log

if [ $? -gt 0 ]; then
    echo "Build failed. See lmc-build-out.log, lorax.log, and ./anaconda/*.log files for details"
    rc=1
else
    echo "Build results in $RESULTS"
    rc=0
fi
exit $rc
