#!/bin/sh

KS_PATH=disk.ks
RESULTS=/var/tmp/lmc-disk-results
BOOT_ISO=/var/tmp/rhel-7.4-boot.iso

# Is libvirtd running?
systemctl status libvirtd > /dev/null
if [ $? -gt 0 ]; then
    echo "Make sure libvirtd is setup and running"
    exit 1
fi

if [ ! -e "$KS_PATH" ]; then
    echo "$KS_PATH is missing"
    exit 1
fi

if [ ! -e "$BOOT_ISO" ]; then
    echo "$BOOT_ISO is missing. You need to copy a RHEL 7.4 boot.iso to $BOOT_ISO"
    exit 1
fi

if [ -e "$RESULTS" ]; then
    echo "Previous results still at $RESULTS, move or delete them first"
    exit 1
fi

getenforce | grep Enforcing > /dev/null
if [ $? -eq 0 ]; then
    echo "SELinux needs to be Permissive or Disabled."
    exit 1
fi

sudo livemedia-creator --iso=$BOOT_ISO \
--title "Red Hat Enterprise Linux" --project "Red Hat Enterprise Linux" --releasever 7.4 \
--make-disk \
--resultdir /var/tmp/lmc-disk-results/ \
--ks=$KS_PATH |& tee lmc-build-out.log

if [ $? -gt 0 ]; then
    echo "Build failed. See lmc-build-out.log, lorax.log, and ./anaconda/*.log files for details"
    rc=1
else
    echo "Build results in $RESULTS"
    rc=0
fi
exit $rc
